import 'svelte-material-ui/bare.css';
import './smui.scss';
import './splitpane.theme.scss';
import 'hover.css';
import 'cooltipz-css';
import 'animate.css';
import 'xterm/css/xterm.css'
import 'ldbutton/index.min.css';
import '@loadingio/loading.css/loading.min.css';
import './global.scss';